# Generated by Django 5.2.17 on 2026-10-04 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('asset_type', models.CharField(choices=[('road', 'Road'), ('bridge', 'Bridge'), ('other', 'Other')], default='road', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('construction_year', models.PositiveIntegerField(blank=True, null=True)),
                ('auto_created', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inspection',
            name='infrastructure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='inspections.infrastructure'),
        ),
    ]
