# Generated by Django 5.2.17 on 2026-10-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_inspection_inspector'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='location_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inspection',
            name='location_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
